os:
  - linux
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - server # build server branch only
before_install:
  - npm install -g hexo-cli
install:
  - npm install
script:
  - hexo generate --force # generate static files
after_success:
  - git config --local user.name "niemingzhao"
  - git config --local user.email "1432440963@qq.com"
  - sed -i "s~git@github.com:~https://${GH_TOKEN}@github.com/~" _config.yml
  - sed -i "s~git@git.dev.tencent.com:~https://niemingzhao:${CO_TOKEN}@git.dev.tencent.com/~" _config.yml
  - hexo deploy > /dev/null
